models/ContactForm.php
<?php

namespace app\models;

use Yii;
use yii\base\Model;

/**
 * ContactForm is the model behind the contact form.
 */
class ContactForm extends Model
{
    public $name;
    public $email;
    public $subject;
    public $body;
    public $verifyCode;


    /**
     * @return array the validation rules.
     */
    public function rules()
    {
        return [
            // name, email, subject and body are required
            [['name', 'email', 'subject', 'body'], 'required'],
            // email has to be a valid email address
            ['email', 'email'],
            // verifyCode needs to be entered correctly
            ['verifyCode', 'captcha'],
        ];
    }

    /**
     * @return array customized attribute labels
     */
    public function attributeLabels()
    {
        return [
            'verifyCode' => 'Verification Code',
        ];
    }

    /**
     * Sends an email to the specified email address using the information collected by this model.
     * @param string $email the target email address
     * @return bool whether the model passes validation
     */
    public function contact($email)
    {
        if ($this->validate()) {
            Yii::$app->mailer->compose()
                ->setTo($email)
                ->setFrom([Yii::$app->params['senderEmail'] => Yii::$app->params['senderName']])
                ->setReplyTo([$this->email => $this->name])
                ->setSubject($this->subject)
                ->setTextBody($this->body)
                ->send();

            return true;
        }
        return false;
    }
}

models/LoginForm.php
<?php

namespace app\models;

use Yii;
use yii\base\Model;

/**
 * LoginForm is the model behind the login form.
 *
 * @property User|null $user This property is read-only.
 *
 */
class LoginForm extends Model
{
    public $username;
    public $password;
    public $rememberMe = true;

    private $_user = false;


    /**
     * @return array the validation rules.
     */
    public function rules()
    {
        return [
            // username and password are both required
            [['username', 'password'], 'required'],
            // rememberMe must be a boolean value
            ['rememberMe', 'boolean'],
            // password is validated by validatePassword()
            ['password', 'validatePassword'],
        ];
    }

    /**
     * Validates the password.
     * This method serves as the inline validation for password.
     *
     * @param string $attribute the attribute currently being validated
     * @param array $params the additional name-value pairs given in the rule
     */
    public function validatePassword($attribute, $params)
    {
        if (!$this->hasErrors()) {
            $user = $this->getUser();

            if (!$user || !$user->validatePassword($this->password)) {
                $this->addError($attribute, 'Incorrect username or password.');
            }
        }
    }

    /**
     * Logs in a user using the provided username and password.
     * @return bool whether the user is logged in successfully
     */
    public function login()
    {
        if ($this->validate()) {
            return Yii::$app->user->login($this->getUser(), $this->rememberMe ? 3600*24*30 : 0);
        }
        return false;
    }

    /**
     * Finds user by [[username]]
     *
     * @return User|null
     */
    public function getUser()
    {
        if ($this->_user === false) {
            $this->_user = User::findByUsername($this->username);
        }

        return $this->_user;
    }
}

models/User.php
<?php

namespace app\models;

class User extends \yii\base\BaseObject implements \yii\web\IdentityInterface
{
    public $id;
    public $username;
    public $password;
    public $authKey;
    public $accessToken;

    private static $users = [
        '100' => [
            'id' => '100',
            'username' => 'admin',
            'password' => 'admin',
            'authKey' => 'test100key',
            'accessToken' => '100-token',
        ],
        '101' => [
            'id' => '101',
            'username' => 'demo',
            'password' => 'demo',
            'authKey' => 'test101key',
            'accessToken' => '101-token',
        ],
    ];


    /**
     * {@inheritdoc}
     */
    public static function findIdentity($id)
    {
        return isset(self::$users[$id]) ? new static(self::$users[$id]) : null;
    }

    /**
     * {@inheritdoc}
     */
    public static function findIdentityByAccessToken($token, $type = null)
    {
        foreach (self::$users as $user) {
            if ($user['accessToken'] === $token) {
                return new static($user);
            }
        }

        return null;
    }

    /**
     * Finds user by username
     *
     * @param string $username
     * @return static|null
     */
    public static function findByUsername($username)
    {
        foreach (self::$users as $user) {
            if (strcasecmp($user['username'], $username) === 0) {
                return new static($user);
            }
        }

        return null;
    }

    /**
     * {@inheritdoc}
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * {@inheritdoc}
     */
    public function getAuthKey()
    {
        return $this->authKey;
    }

    /**
     * {@inheritdoc}
     */
    public function validateAuthKey($authKey)
    {
        return $this->authKey === $authKey;
    }

    /**
     * Validates password
     *
     * @param string $password password to validate
     * @return bool if password provided is valid for current user
     */
    public function validatePassword($password)
    {
        return $this->password === $password;
    }
}

controllers/SiteController.php
<?php

namespace app\controllers;

use Yii;
use yii\filters\AccessControl;
use yii\web\Controller;
use yii\web\Response;
use yii\filters\VerbFilter;
use app\models\LoginForm;
use app\models\ContactForm;

class SiteController extends Controller
{
    /**
     * {@inheritdoc}
     */
    public function behaviors()
    {
        return [
            'access' => [
                'class' => AccessControl::className(),
                'only' => ['logout'],
                'rules' => [
                    [
                        'actions' => ['logout'],
                        'allow' => true,
                        'roles' => ['@'],
                    ],
                ],
            ],
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'logout' => ['post'],
                ],
            ],
        ];
    }

    /**
     * {@inheritdoc}
     */
    public function actions()
    {
        return [
            'error' => [
                'class' => 'yii\web\ErrorAction',
            ],
            'captcha' => [
                'class' => 'yii\captcha\CaptchaAction',
                'fixedVerifyCode' => YII_ENV_TEST ? 'testme' : null,
            ],
        ];
    }

    /**
     * Displays homepage.
     *
     * @return string
     */
    public function actionIndex()
    {
        return $this->render('index');
    }

    /**
     * Login action.
     *
     * @return Response|string
     */
    public function actionLogin()
    {
        if (!Yii::$app->user->isGuest) {
            return $this->goHome();
        }

        $model = new LoginForm();
        if ($model->load(Yii::$app->request->post()) && $model->login()) {
            return $this->goBack();
        }

        $model->password = '';
        return $this->render('login', [
            'model' => $model,
        ]);
    }

    /**
     * Logout action.
     *
     * @return Response
     */
    public function actionLogout()
    {
        Yii::$app->user->logout();

        return $this->goHome();
    }

    /**
     * Displays contact page.
     *
     * @return Response|string
     */
    public function actionContact()
    {
        $model = new ContactForm();
        if ($model->load(Yii::$app->request->post()) && $model->contact(Yii::$app->params['adminEmail'])) {
            Yii::$app->session->setFlash('contactFormSubmitted');

            return $this->refresh();
        }
        return $this->render('contact', [
            'model' => $model,
        ]);
    }

    /**
     * Displays about page.
     *
     * @return string
     */
    public function actionAbout()
    {
        return $this->render('about');
    }

     public function actionServices()
    {
        return $this->render('services');
    }
    
      public function actionClients()
    {
        return $this->render('clients');
    }
}

views/layouts/main.php
<?php

/* @var $this \yii\web\View */
/* @var $content string */

use app\widgets\Alert;
use yii\helpers\Html;
use yii\bootstrap\Nav;
use yii\bootstrap\NavBar;
use yii\widgets\Breadcrumbs;
use app\assets\AppAsset;

AppAsset::register($this);
?>
<?php $this->beginPage() ?>
<!DOCTYPE html>
<html lang="<?= Yii::$app->language ?>">
<head>
    <meta charset="<?= Yii::$app->charset ?>">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <?php $this->registerCsrfMetaTags() ?>
    <title><?= Html::encode($this->title) ?></title>
    <?php $this->head() ?>
</head>
<body>
<?php $this->beginBody() ?>

<div class="wrap">
   <header>
            <div class="container-fluid p-0">
                <nav class="navbar navbar-expand-lg">
                    <a class="nav-link" href="#">
                    <i class='fas fa-book-reader'></i>
                    Books</a>
                    <div class="collapse navbar-collapse" id="navbarNav">
                        <div class="mr-auto"></div>
                        <ul class="navbar-nav">
                            <li class="nav-item active">
                                <?=Html::a('Home',['site/index'])?>
                            </li>
                            <li class="nav-item">
                                 <?=Html::a('About Us',['site/about'])?>
                            </li>
                            <li class="nav-item">
                               <?=Html::a('Our Services',['site/services'])?>
                            </li>
                            <li class="nav-item">
                                <?=Html::a('Contact Us',['site/contact'])?>
                            </li>
                            <li class="nav-item">
                                <?=Html::a('Happy Clients',['site/clients'])?>
                            </li>
                            
                        </ul>
                    </div>
                </nav>
            </div>
            <div class="container text-center">
                <div class="row">
                    <div class="col-md-7 col-xs-7 col-sm-12">
                        <h6>AUTHOR: DAILY TUTION</h6>
                        <h1>EXCITING ADVENTURE</h1>
                        <p>
                            Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod
                            tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam,
                            quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo
                            consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse
                            cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non
                            proident, sunt in culpa qui officia deserunt mollit anim id est laborum.
                        </p>
                        <button class="btn btn-light px-5 py-2">By now for $8.99</button>
                    </div>
                    <div class="col-md-5 col-xs-5 col-sm-12">
                        <img src="Images/book.jpg" alt="Books" style="height: 250px;">
                    </div>
                </div>
            </div>

          
            
        </header>

    <div class="container">
        <?= Breadcrumbs::widget([
            'links' => isset($this->params['breadcrumbs']) ? $this->params['breadcrumbs'] : [],
        ]) ?>
        <?= Alert::widget() ?>
        <?= $content ?>
    </div>
</div>

<footer >
    <div class="container-fluid p-0">
        <div class="row text-left">
            <div class="col-md-5 col-md-5">
                <h1 class="text-light">About Us</h1>
                <p class="text-muted">
                    Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod
                    tempor incididunt ut labore et dolore magna aliqua.
                </p>
                <p class="text-muted">
                    Copyright @2019 All rights reserved | 
                    <span>Books.edu.np</span>
                </p>
            </div>
            <div class="col-md-5">
                <h4 class="text-muted">Newsletter</h4>
                <p class="text-muted">Stay Updated</p>
                <form class="form-inline">
                <div class="col pl-">
                    <div class="input-group pr-5">
                        <input type="text" class="form-control bg-dark text-white" placeholder="Email">
                        <div class="input-group-prepend">
                            <div class="input-group-text">
                                <i class='fas fa-arrow-right' style='font-size:24px; color: dodgerblue;'></i>
                                
                            </div>
                        </div>
                    </div>
                    
                </div>                  
                </form>
                
            </div>
            <div class="col-md-2 col-sm-12">
                <h4 class="text-light">Follow Us</h4>
                <p class="text-muted">Let us be social</p>
                <div class="column">
                    <i class="fa fa-facebook-f"></i>
                    <i class="fa fa-instagram"></i>
                    <i class="fa fa-twitter"></i>
                    <i class="fa fa-youtube"></i>
                    
                </div>
                
            </div>
            
        </div>
    </div>
</footer>

<?php $this->endBody() ?>
</body>
</html>
<?php $this->endPage() ?>

views/site/Clients.php
<main>

	<center>
		<div class="logo">
			<h1>Our Clients</h1>
		</div>

<div class="happyclient">
		<div class="row">
			
			<div class="col-md-4 col-xs-4 col-sm-12">
				<div class="logo1">
					<div class="container">
						<img src="https://image.freepik.com/free-vector/luxury-letter-e-logo-design_1017-8903.jpg" class="img-thumbnail">
						<div class="overlay">
							<marquee class="text">Excepteur sint occaecat cupidatat non
							proident</marquee>
						</div>
					</div>
				</div>
			</div>
			
			<div class="col-md-4 col-xs-4 col-sm-12">
				<div class="logo1">

					<div class="container">
						<img src="https://image.freepik.com/free-vector/blue-tech-logo_1103-825.jpg" class="img-thumbnail">
						<div class="overlay">
							<marquee class="text">Excepteur sint occaecat cupidatat non
							proident</marquee>
						</div>
					</div>
				</div>
			</div>

			<div class="col-md-4 col-xs-4 col-sm-12">
				<div class="logo1">


					<div class="container">
						<img src="https://image.freepik.com/free-vector/football-logo-background_1195-244.jpg" class="img-thumbnail">
						<div class="overlay">
							<marquee class="text">Excepteur sint occaecat cupidatat non
							proident</marquee>
						</div>
					</div>
				</div>

			</div>
		</div>




		<div class="row">
			<div class="col-md-4 col-xs-4 col-sm-12">
				<div class="logo2">
					<div class="container">
						<img src="https://image.freepik.com/free-vector/blue-tech-logo_1103-822.jpg" class="img-thumbnail">
						<div class="overlay">
							<marquee class="text">Excepteur sint occaecat cupidatat non
							proident</marquee>
						</div>
					</div>
				</div>
			</div>
			<div class="col-md-4 col-xs-4 col-sm-12">
				<div class="logo2">
					<div class="container">
						<img src="https://image.freepik.com/free-vector/background-of-spots-halftone_1035-3847.jpg" class="img-thumbnail">
						<div class="overlay">
							<marquee class="text">Excepteur sint occaecat cupidatat non
							proident</marquee>
						</div>
					</div>
				</div>
			</div>
			<div class="col-md-4 col-xs-4 col-sm-12">
				<div class="logo2">
					<div class="container">
						<img src="https://image.freepik.com/free-vector/3d-box-logo_1103-876.jpg" class="img-thumbnail">
						<div class="overlay">
							<marquee class="text">Excepteur sint occaecat cupidatat non
							proident</marquee>
						</div>
					</div>
				</div>
			</div>
			
		</div>
	</div>
</div>
	
</center>




</main>

views/site/Services.php
<main>
			<div>
				<div>
					<img src="Images/book3.jpg" alt="member" style="width: 100%; height: 500px;" class="img-fluid border-radius p-4">
				</div>
				<div>
					<Center>
						<h1>Our Services</h1>
					</Center>
					<div class="manila">
						<div class="row">
					
							<div class="col-md-4 col-xs-4 col-sm-12 text-center">
								<div class="card">
									<img src="Images/book.jpg" alt="John" style="width:100%">
									<i class="fa fa-hand-o-down" style="font-size: 30px;"></i>
									<h4 class="a">BOOKS MONTHLY BOOKKEEPING</h4>
									<p class="tittle">I have my income and expenses, now what?  We're here to help create a smooth-running, monthly process for you.  This will include importing your transactions through a Quickbooks/Bank sync, </p>
								</div>
							</div>	
							<div class="col-md-4 col-xs-4 col-sm-12 text-center">
								<div class="card">
									<img src="Images/book.jpg" alt="John" style="width:100%">
									<i class="fa fa-hand-o-down" style="font-size: 30px;"></i>
									<h4 class="a">BOOKS SET UP</h4>
									<p class="tittle">Are you looking to start working in Quickbooks? Or do you need help switching from Quickbooks Desktop to Online? Or do you need help switching from Quickbooks Desktop to Online? </p>
								</div>
								

							</div>	
							<div class="col-md-4 col-xs-4 col-sm-12 text-center">
								<div class="card">
									<img src="Images/book.jpg" alt="John" style="width:100%">
									<i class="fa fa-hand-o-down" style="font-size: 30px;"></i>
									<h4 class="a">BOOKS TRAINING & SUPPORT </h4>
									<p class="tittle">But I want to learn how to do it myself... Great! We'd love to help you take control of your own business!  
									 clients so that they not only understand what we do, </p>
								</div>
								
							</div>
							
						</div>
					
					
						<div class="row">

							<div class="col-md-4 col-xs-4 col-sm-12 text-center">
									<div class="card">
										<img src="Images/book.jpg" alt="John" style="width:100%">
										<i class="fa fa-hand-o-down" style="font-size: 30px;"></i>
										<h4 class="a">BOOKS MONTHLY BOOKKEEPING</h4>
										<p class="tittle">I have my income and expenses, now what?This will include importing your transactions through a Quickbooks and monthly reports so you know just how much money you've spent and made each month.</p>
									</div>
								</div>	
								<div class="col-md-4 col-xs-4 col-sm-12 text-center">
									<div class="card">
										<img src="Images/book.jpg" alt="John" style="width:100%">
										<i class="fa fa-hand-o-down" style="font-size: 30px;"></i>
										<h4 class="a">BOOKS SET UP</h4>
										<p class="tittle">Are you looking to start working in Quickbooks? Or do you need help switching from Quickbooks Desktop to Online?  Either way,Are you looking to start working in Quickbooks? </p>
									</div>
									

								</div>	
								<div class="col-md-4 col-xs-4 col-sm-12 text-center">
									<div class="card">
										<img src="Images/book.jpg" alt="John" style="width:100%">
										<i class="fa fa-hand-o-down" style="font-size: 30px;"></i>
										<h4 class="a">BOOKS TRAINING & SUPPORT </h4>
										<p class="tittle">But I want to learn how to do it myself... Great! We'd love to help you take control of your own business!  work themselves they so choose. </p>
									</div>
									
								</div>
						</div>
						</div>
					</div>
				</div>
			</div>
		</main>

views/site/about.php
<div class="aboutus-section">
        <div class="container">
            <div class="row">
                <div class="col-md-3 col-sm-6 col-xs-12">
                    <div class="aboutus">
                        <h2 class="aboutus-title">About Us</h2>
                        <p class="aboutus-text">Aenean vulputate eleifend tellus. Aenean leo ligula, porttitor eu, consequat vitae, eleifend ac, enim. Aliquam lorem ante, dapibus in.</p>
                        <p class="aboutus-text">This is Photoshop's version of Lorem Ipsum. Proin gravida nibh vel velit auctor aliquet. Aenean sollicitudin, lorem quis bibendum auctor, nisi elit consequat ipsum, nec sagittis sem</p>
                        <a class="aboutus-more" href="#">read more</a>
                    </div>
                </div>
                <div class="col-md-3 col-sm-6 col-xs-12">
                    <div class="aboutus-banner">
                        <img src="Images/c1.jpg">
                    </div>
                </div>
                <div class="col-md-5 col-sm-6 col-xs-12">
                    <div class="feature">
                        <div class="feature-box">
                            <div class="clearfix">
                                <div class="iconset">
                                    <span class="glyphicon glyphicon-cog icon"></span>
                                </div>
                                <div class="feature-content">
                                    <h4>Work with heart</h4>
                                    <p>Aenean vulputate eleifend tellus. Aenean leo ligula, porttitor eu, consequat vitae, eleifend ac, enim. Aliquam lorem ante, dapibus in.</p>
                                </div>
                            </div>
                        </div>
                        <div class="feature-box">
                            <div class="clearfix">
                                <div class="iconset">
                                    <span class="glyphicon glyphicon-cog icon"></span>
                                </div>
                                <div class="feature-content">
                                    <h4>Reliable services</h4>
                                    <p>Donec vitae sapien ut libero venenatis faucibu. Nullam quis ante. Etiam sit amet orci eget eros faucibus tincidunt</p>
                                </div>
                            </div>
                        </div>
                        <div class="feature-box">
                            <div class="clearfix">
                                <div class="iconset">
                                    <span class="glyphicon glyphicon-cog icon"></span>
                                </div>
                                <div class="feature-content">
                                    <h4>Great support</h4>
                                    <p>Aenean vulputate eleifend tellus. Aenean leo ligula, porttitor eu, consequat vitae, eleifend ac, enim. Aliquam lorem ante, dapibus in.</p>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>

views/site/contact.php
<main>
            <div class="maincontact">
                <center>
                    <div class="contact">Contact Us</div>
                </center>

                <div class="row">

                    <div class="col-md-4 col-xs-4 col-sm-12">
                        <center>
                            <img src="Images/c1.jpg" class="c">
                            <h2 class="c1"> By Phone</h2>
                            <div>(Monday to Saturday; 11pm to 4pm )</div>
                            <div class="c2">
                            Contact No: 9808892646
                                        9807546789
                            </div>
                        </center>
                    </div>
                    <div class="col-md-4 col-xs-4 col-sm-12">
                        <center>
                            <img src="Images/c2.jpg" class="c">
                            <h2 class="c1"> Start a new case</h2>
                            <p class="c2">
                                Just send us your questions or concerns by starting 
                                a new case and we will give you the help you need.
                            </p>
                            <div class="c3">
                                <button type="start" class="btn">Start Here</button>
                            </div>
                        </center>
                    </div>
                    <div class="col-md-4 col-xs-4 col-sm-12">
                        <center>
                            <img src="Images/c3.jpg" class="c">
                            <h2 class="c1"> Live chat</h2>
                            <p class="c2">
                                Chat with a member of our in-house team.
                            </p>
                            <div class="c3">
                                <button type="start" class="btn">Start Chat</button>
                            </div>
                        </center>
                    </div>
                    
                </div>

            </div>

            <div>
                <center>
                    <div class="contact">Track a Case</div>
                        <p class="c4">View your thread of messages with our support team.</p>
                        <div class="container contact-form">
                            <div class="contact-image">
                                <img src="https://image.ibb.co/kUagtU/rocket_contact.png" alt="rocket_contact"/>
                            </div>
                            <form method="post">
                                <h3>Drop Us a Message</h3>
                                <div class="row">
                                    <div class="col-md-6">
                                        <div class="form-group">
                                            <input type="text" name="txtName" class="form-control" placeholder="Your Name *" value="" />
                                        </div>
                                        <div class="form-group">
                                            <input type="text" name="txtEmail" class="form-control" placeholder="Your Email *" value="" />
                                        </div>
                                        <div class="form-group">
                                            <input type="text" name="txtPhone" class="form-control" placeholder="Your Phone Number *" value="" />
                                        </div>
                                        <div class="form-group">
                                            <input type="submit" name="btnSubmit" class="btnContact" value="Send Message" />
                                        </div>
                                    </div>
                                    <div class="col-md-6">
                                        <div class="form-group">
                                            <textarea name="txtMsg" class="form-control" placeholder="Your Message *" style="width: 100%; height: 150px;"></textarea>
                                        </div>
                                    </div>
                                </div>
                            </form>
                        </div>
                     
                    </div>

                </center>

            </div>
        
        </main>

views/site/error.php
<?php

/* @var $this yii\web\View */
/* @var $name string */
/* @var $message string */
/* @var $exception Exception */

use yii\helpers\Html;

$this->title = $name;
?>
<div class="site-error">

    <h1><?= Html::encode($this->title) ?></h1>

    <div class="alert alert-danger">
        <?= nl2br(Html::encode($message)) ?>
    </div>

    <p>
        The above error occurred while the Web server was processing your request.
    </p>
    <p>
        Please contact us if you think this is a server error. Thank you.
    </p>

</div>